language: php
sudo: false
php:
  - 7.4
  - 7.0
before_install:
  - export PATH="$PATH:$(composer global config bin-dir --absolute)"
  - composer global require "squizlabs/php_codesniffer=3.*"
  - phpenv rehash
script:
  - phpcs -p --extensions=php --standard="`pwd`/CodeSniff/WCF" .
