language: php
sudo: false
php:
  - 5.6
  - 5.3
before_install:
  - export PATH="$PATH:$(composer global config bin-dir --absolute)"
  - composer global require "squizlabs/php_codesniffer=2.*"
  - phpenv rehash
script:
  - find . -type f -name '*.php' -print0 |xargs -0 -I file -P 4 php -l file > /dev/null
  - phpcs -p --extensions=php --standard="`pwd`/CodeSniff/WCF" .
